### ISSUE TITLE
Automatic upgrade is not working

### ISSUE THREAD

**Issue by SadE54** [esofthead/mycollab#5]
Hi,

MyCollab tried today to update itself to 5.0. 6 at start (I'm not using a service , but the Win startup batch) but it's blocking - even If I'm waiting 1 hour. I had the same problem from 5.04 to 5.05 , and had to reinstall manually (and start with a new database :-/) . The log file seems to be erased during the update process so I joined a picture of the Java app :
![update bug](https://cloud.githubusercontent.com/assets/2878768/7510048/09fa44ee-f44d-11e4-9958-e2c2845239cc.png)

**Comment by haiphucnguyen** [comment]
Thank you for reporting, this is a bug on windows. We is investigating and try to fix at this weekend. By the mean time,  you can download the new MyCollab version manual on Sourceforge, install (unzip the setup file then run the exe file) and copy the mycollab.properties file from %MYCOLLAB_FOLDER%/conf to the new conf folder. The MyCollab 5.0.6 addressed many issues of installation on Windows and we are trying to install every major Windows versions to test the installation and upgrade process.

**Comment by haiphucnguyen** [comment]
This issue is fixed on MyCollab 5.0.7 https://sourceforge.net/projects/mycollab/?source=navbar. It was tested on various Windows versions. You could only check this feature from the higher MyCollab version. From the MyCollab 5.0.6 and below, user should to upgrade MyCollab manually http://community.mycollab.com/upgrade/
